/* eslint-disable @typescript-eslint/no-require-imports -- isolierter PostgreSQL-Integrationstest. */
const assert = require("node:assert/strict");
const Module = require("node:module");
if (!process.env.DATABASE_URL?.startsWith("postgresql://bezirketest@127.0.0.1:54329/")) throw new Error("Nur die isolierte bezirketest-Datenbank ist zulässig.");
process.env.JWT_SECRET ||= "test-geheimnis-mit-mindestens-zweiunddreissig-zeichen";
const cookie = new Map(); const original = Module._load;
Module._load = function (request, parent, main) {
  if (request === "server-only") return {};
  if (request === "next/headers") return { cookies: async () => ({ get: (k) => cookie.has(k) ? { value: cookie.get(k) } : undefined, set: (k, v) => cookie.set(k, v), delete: (k) => cookie.delete(k) }) };
  if (request === "next/cache") return { revalidatePath() {} };
  return original.call(this, request, parent, main);
};
require("tsx/cjs");
const { prisma } = require("../src/lib/prisma");
const { signToken, setSessionCookie, clearSessionCookie } = require("../src/lib/auth");
const { bereiteArchivpaketVor, bestaetigeArchivuebernahme, erteileArchivnachfrist } = require("../src/actions/archiv");
const { ladeArchivInhalt, archivinhaltsHash, paketkennung } = require("../src/lib/archiv");
const { runRetention } = require("../src/lib/retention");
const prefix = `archiv-test-${Date.now()}`;
const login = async (user) => setSessionCookie(await signToken(user.id, user.sessionVersion));
const form = (werte) => { const f = new FormData(); for (const [k,v] of Object.entries(werte)) f.set(k, String(v)); return f; };
(async () => {
  const [a, b] = await Promise.all([prisma.bezirk.create({ data: { name: `${prefix}-A`, kuerzel: `${prefix}a` } }), prisma.bezirk.create({ data: { name: `${prefix}-B`, kuerzel: `${prefix}b` } })]);
  const admin = await prisma.user.create({ data: { email: `${prefix}@test.invalid`, role: "ADMIN", isActive: true, mfaAktiviertAm: new Date(), bezirke: { connect: { id: a.id } } } });
  const ort = await prisma.veranstaltungsort.create({ data: { name: `${prefix}-Ort`, ort: "Test" } });
  const make = (bezirkId, titel) => prisma.fortbildung.create({ data: { slug: `${prefix}-${titel}-${Math.random()}`, titel, beschreibungHtml: "<p>x</p>", beschreibungText: "x", organisationsform: "SCHILF", maxTn: 12, format: "PRAESENZ", beginn: new Date("2020-09-01T09:00:00Z"), ende: new Date("2020-09-01T11:00:00Z"), veranstaltungsortId: ort.id, schularten: ["GRUNDSCHULE"], status: "VEROEFFENTLICHT", bezirkId } });
  const fOhne = await make(a.id, "ohne"); const fB = await make(b.id, "fremd");
  await prisma.fortbildung.updateMany({ where: { id: { in: [fOhne.id, fB.id] } }, data: { aufbewahrenBis: new Date("2021-01-01T00:00:00Z") } });
  await login(admin);
  assert.ok((await bereiteArchivpaketVor({}, b.id, "2020/2021")).fehler, "fremder Bezirk bleibt gesperrt");
  assert.ok((await bereiteArchivpaketVor({}, a.id, "2020/2021")).fehler, "abgelaufene Daten benötigen Nachfrist");
  const freigabe = form({ bezirkId: a.id, schuljahr: "2020/2021", begruendung: "Test einer begründeten verspäteten Übernahme" });
  assert.ok((await erteileArchivnachfrist({}, freigabe)).fehler, "BdB darf keine eigene Nachfrist erteilen");
  await prisma.user.update({ where: { id: admin.id }, data: { role: "RVS" } });
  assert.equal((await erteileArchivnachfrist({}, freigabe)).erfolg, true);
  await prisma.user.update({ where: { id: admin.id }, data: { role: "ADMIN" } });
  assert.equal((await bereiteArchivpaketVor({}, a.id, "2020/2021")).erfolg, true);
  const { NextRequest } = require("next/server");
  const route = require("../src/app/api/admin/archiv/download/route");
  const anfrage = new NextRequest(`http://localhost/api/admin/archiv/download?bezirkId=${a.id}&schuljahr=2020`);
  const antwort = await route.GET(anfrage);
  assert.equal(antwort.status, 200);
  const bytes = Buffer.from(await antwort.arrayBuffer());
  const JSZip = require("jszip");
  const zip = await JSZip.loadAsync(bytes);
  const json = await zip.file("fortbildungen.json").async("nodebuffer");
  const summe = require("node:crypto").createHash("sha256").update(json).digest("hex");
  assert.ok((await zip.file("pruefsumme.sha256").async("string")).startsWith(summe));
  const wiederholt = Buffer.from(await (await route.GET(anfrage)).arrayBuffer());
  assert.deepEqual(bytes, wiederholt, "ZIP-Bytes sind reproduzierbar");
  const csv = require("../src/lib/archiv").archivinhaltsCsv;
  const testInhalt = await ladeArchivInhalt(a.id, 2020);
  testInhalt.fortbildungen[0].titel = "=HYPERLINK(1)";
  assert.ok(csv(testInhalt).includes("'=HYPERLINK(1)"), "CSV neutralisiert Formeln");
  const inhalt = await ladeArchivInhalt(a.id, 2020); const hash = archivinhaltsHash(inhalt); const kennung = paketkennung(a.id, 2020, hash);
  await prisma.archivpaket.upsert({ where: { bezirkId_schuljahr: { bezirkId: a.id, schuljahr: 2020 } }, create: { bezirkId: a.id, schuljahr: 2020, paketkennung: kennung, inhaltsHash: hash, anzahl: 1 }, update: { paketkennung: kennung, inhaltsHash: hash, anzahl: 1 } });
  await prisma.fortbildung.update({ where: { id: fOhne.id }, data: { titel: "geändert" } });
  const alt = await bestaetigeArchivuebernahme({}, form({ bezirkId: a.id, schuljahr: "2020/2021", paketkennung: kennung, inhaltsHash: hash, externeAblage: "Testarchiv", lesbarkeitBestaetigt: "on" }));
  assert.ok(alt.fehler, "geänderte Daten entwerten den alten Hash");
  const aktuell = await ladeArchivInhalt(a.id, 2020); const aktuellHash = archivinhaltsHash(aktuell); const aktuellKennung = paketkennung(a.id, 2020, aktuellHash);
  // Bestätigte Kohorte löschen; parallele Wiederholung erzeugt keinen zweiten Nachweis.
  const bestätigung = form({ bezirkId: a.id, schuljahr: "2020/2021", paketkennung: aktuellKennung, inhaltsHash: aktuellHash, externeAblage: "Testarchiv", lesbarkeitBestaetigt: "on" });
  const ersteBestaetigung = await bestaetigeArchivuebernahme({}, bestätigung);
  assert.equal(ersteBestaetigung.erfolg, true, ersteBestaetigung.fehler);
  const zweiteBestaetigung = await bestaetigeArchivuebernahme({}, bestätigung);
  assert.equal(zweiteBestaetigung.erfolg, true, zweiteBestaetigung.fehler);
  assert.equal(await prisma.archivuebernahme.count({ where: { archivpaket: { bezirkId: a.id, schuljahr: 2020 }, inhaltsHash: aktuellHash } }), 1, "Bestätigung ist idempotent");
  await runRetention();
  assert.equal(await prisma.fortbildung.count({ where: { id: fOhne.id } }), 0, "gültig übernommene Kohorte wird gelöscht");
  assert.equal(await prisma.fortbildung.count({ where: { id: fB.id } }), 1, "ohne Übergabe bleibt die fremde Kohorte erhalten");
  await clearSessionCookie();
  await prisma.$transaction([prisma.fortbildung.deleteMany({ where: { slug: { startsWith: prefix } } }), prisma.archivpaket.deleteMany({ where: { bezirkId: a.id } }), prisma.archivnachfristFreigabe.deleteMany({ where: { bezirkId: { in: [a.id, b.id] } } }), prisma.bezirk.deleteMany({ where: { id: { in: [a.id, b.id] } } }), prisma.veranstaltungsort.delete({ where: { id: ort.id } }), prisma.user.delete({ where: { id: admin.id } })]);
  console.log("Archiv-Integrationstests erfolgreich.");
})().catch(async (e) => { console.error(e); await prisma.$disconnect(); process.exitCode = 1; }).finally(() => prisma.$disconnect());
